---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: ack-organizations-reader
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - organizations.services.k8s.aws
  resources:
  - accounts
  - organizationalunits
  verbs:
  - get
  - list
  - watch
