---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: ack-organizations-writer
  namespace: default
rules:
- apiGroups:
  - organizations.services.k8s.aws
  resources:
  - accounts
  - organizations
  - organizationalunits
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - organizations.services.k8s.aws
  resources:
  - accounts
  - organizations
  - organizationalunits
  verbs:
  - get
  - patch
  - update
