---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: ack-organizations-reader
  namespace: default
rules:
- apiGroups:
  - organizations.services.k8s.aws
  resources:
  - organizations
  - organizationalunits
  verbs:
  - get
  - list
  - watch
