# This configuration is a placeholder. Replace any values with relevant values for your
# service controller project.
---
annotations:
  capabilityLevel: Basic Install
  shortDescription: AWS Organizations controller is a service controller for managing Organizations resources
    in Kubernetes
displayName: AWS Controllers for Kubernetes - Amazon Organizations
description: |-
  Manage Amazon Organizations resources in AWS from within your Kubernetes cluster.


  **About Amazon Organizations**


  With AWS Organizations you can perform account management activities at scale by consolidating multiple AWS accounts into a single organization.
  Consolidating accounts simplifies how you use other AWS services. You can leverage the multi-account management services available in AWS Organizations
  with select AWS services to perform tasks on all accounts that are members of your organization.


  **About the AWS Controllers for Kubernetes**


  This controller is a component of the [AWS Controller for Kubernetes](https://github.com/aws/aws-controllers-k8s)
  project. This project is currently in **developer preview**.
samples:
- kind: OrganizationalUnit
  spec: '{}'
maintainers:
- name: "organizations maintainer team"
  email: "ack-maintainers@amazon.com"
links:
- name: Amazon Organizations Developer Resources
  url: https://aws.amazon.com/organizations/resources/
